# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QZPPyA7n7HdNAIrjDQfr2ZTjm918CclF
"""

x = int(input("Istalgan son kiriting:\n>>>"))
print(x, " ning kvadrati ", x ** 2, " ga teng")
print(x, " ning kubi ", x ** 3, " ga teng")

